USE master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE Name='LAB2')
DROP DATABASE LAB2
GO
CREATE DATABASE LAB2
GO
USE LAB2
GO

CREATE TABLE PHONGBAN (
MaPB INT IDENTITY PRIMARY KEY,
TenPB nvarchar(50)
);

CREATE TABLE NHANVIEN (
MaNV INT IDENTITY PRIMARY KEY,
TenNV nvarchar(50),
NgaySinh datetime,
SoCMND char(9),
GioiTinh char(1),
DiaChi nvarchar(100),
NgayVaoLam datetime,
MaPB INT,
CONSTRAINT MaPB FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LUONGDA (
MaDA INT IDENTITY PRIMARY KEY,
MaNV INT,
NgayNhan datetime NOT NULL,
SoTien money,
CONSTRAINT MaNV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE CASCADE ON UPDATE CASCADE 
);
