USE Master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE Name='SLOT10')
DROP DATABASE SLOT10
GO
CREATE DATABASE SLOT10
GO
USE SLOT10
GO


CREATE TABLE Student(
 SID INTEGER IDENTITY PRIMARY KEY, 
 S_FName VARCHAR(20) NOT NULL,
 S_LName VARCHAR(30) NOT NULL
);
CREATE TABLE Course(
 CID INTEGER IDENTITY PRIMARY KEY, 
 C_Name VARCHAR(30) NOT NULL
);
CREATE TABLE Course_Grades(
 CGID INTEGER IDENTITY PRIMARY KEY, 
 Semester CHAR(4) NOT NULL, 
 CID_CG INTEGER NOT NULL, 
 SID_CG INTEGER NOT NULL,
 Grade CHAR(2) NOT NULL, 
 CONSTRAINT CID_CG_FK
 FOREIGN KEY (CID_CG)
 REFERENCES Course(CID)
 ON DELETE CASCADE,
 CONSTRAINT SID_CG_FK
 FOREIGN KEY (SID_CG)
 REFERENCES Student(SID)
 ON DELETE CASCADE
);
